/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Promocode } from "./Promocode";
import { PromocodeCountArgs } from "./PromocodeCountArgs";
import { PromocodeFindManyArgs } from "./PromocodeFindManyArgs";
import { PromocodeFindUniqueArgs } from "./PromocodeFindUniqueArgs";
import { DeletePromocodeArgs } from "./DeletePromocodeArgs";
import { PromocodeService } from "../promocode.service";
@graphql.Resolver(() => Promocode)
export class PromocodeResolverBase {
  constructor(protected readonly service: PromocodeService) {}

  async _promocodesMeta(
    @graphql.Args() args: PromocodeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Promocode])
  async promocodes(
    @graphql.Args() args: PromocodeFindManyArgs
  ): Promise<Promocode[]> {
    return this.service.promocodes(args);
  }

  @graphql.Query(() => Promocode, { nullable: true })
  async promocode(
    @graphql.Args() args: PromocodeFindUniqueArgs
  ): Promise<Promocode | null> {
    const result = await this.service.promocode(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Promocode)
  async deletePromocode(
    @graphql.Args() args: DeletePromocodeArgs
  ): Promise<Promocode | null> {
    try {
      return await this.service.deletePromocode(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
